// Dados organizados por classe e disciplina com links convertidos para embeddedfolderview
export const driveLinks = {
  "7": {
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1OPs3eEolF74hMP4idDMXf_nkLq5ZiTud#list",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1AXolnDK_45PWzwqx9XboiUFx2-Lg1V8B#list",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1hnzNHKrrkIdnmIgR3A8SsHvfNPTQcxlJ#list",
    Física: "https://drive.google.com/embeddedfolderview?id=1EunIY_c77MO8ebAYuNPjHOFHsZBAdkm8#list",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1y4vLsIcHJUdcplr1B1bDMhh_UbO6nCPu#list",
    História: "https://drive.google.com/embeddedfolderview?id=12fS48y2G7o7w_kI1S8Gl9_pot53_4Nsc#list",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1f0Ur2aRkcJLUreyInf9OL6Nzilij6-qj#list",
    Matemática: "https://drive.google.com/embeddedfolderview?id=142J3A4WaKhJrdXGHLa_S64wGCJ-OYvh6#list",
    Química: "https://drive.google.com/embeddedfolderview?id=1oXViKXWsmNLMA8LTjn5M36coZA3eb7xW#list",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=1U0FIeYsGbcTN44Y-OLPFciiNxUJSlX1l#list",
  },
  "8": {
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1L4SlK7PqGblqqSM9ARIZfw8WZYOdNoG5#list",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1oyCxsd1rklg4fK4qfngvrtyRm4YqvlXa#list",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1EH2TIk8_O0wCGdW4d53K4GgGp2fW_3ne#list",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1EH2TIk8_O0wCGdW4d53K4GgGp2fW_3ne#list",
    Física: "https://drive.google.com/embeddedfolderview?id=1nNngc6I4TwNsyXTshR3INkRpv7e0tTlw#list",
    Francês: "https://drive.google.com/embeddedfolderview?id=1nNngc6I4TwNsyXTshR3INkRpv7e0tTlw#list",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1E46aPoE1GJGnNav0C529EZO9NOMRST3k#list",
    História: "https://drive.google.com/embeddedfolderview?id=16B96Jh_dCZTcNJT1qLvuWtvLnPBZtixj#list",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1EdXSnug3mGrVCL6TMG1wxFqU6St18HYX#list",
    Matemática: "https://drive.google.com/embeddedfolderview?id=1bEo6gmLhwwj8ipD-ZSeI-Ku19qYRXviA#list",
    Português: "https://drive.google.com/embeddedfolderview?id=1hMkQyeg6uwTqAyTx_qvXNFQYYHsd6wl2#list",
    Química: "https://drive.google.com/embeddedfolderview?id=1nMzI30aZ2OwrZPz0T-DqCSqPtX3r2K4v#list",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=1mFJqkPgj5_NPqrHpdtu5SPjbbZ0eh_UX#list",
  },
  "9": {
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=16oNimQladjjAsJkKUjk6RoaeY2ko4tnM#list",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1j2QcwJDspT1ez-7aCK2S3Xd-uFNXmx5P#list",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1K0fZSjMGoyHbqesSuIAKQLlsuA89nS4w#list",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1K0fZSjMGoyHbqesSuIAKQLlsuA89nS4w#list",
    Física: "https://drive.google.com/embeddedfolderview?id=17AtSatgnAipSET7DX97-0akM208iYs25#list",
    Francês: "https://drive.google.com/embeddedfolderview?id=1D1Z9Zoe0uHB7IrGMe4RSeFfE_N3JGYdC#list",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1D1Z9Zoe0uHB7IrGMe4RSeFfE_N3JGYdC#list",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1YO5pN5TY9LGXxVw01cNj9sYbfz-Pv4JV#list",
    Matemática: "https://drive.google.com/embeddedfolderview?id=1I3qsHGKO_a6bfwep8CKbCk3_hbnEIQIr#list",
    Português: "https://drive.google.com/embeddedfolderview?id=19mVLWWktplhwLp2aIKbaFhbvouwCvinx#list",
    Química: "https://drive.google.com/embeddedfolderview?id=1UpsfIlDwHUbWGEb-iGytW5pBxor2v25X#list",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=19tFVkiJziUtTgN2gaUTtfCj4MdG_oDHB#list",
  },
  "10": {
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1JjgMeaOwVDdYv86yWhKzSLfwFk2SCf4F#list",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1hcfYAvtB0m2583wSM_MASJS7tNTmHeDf#list",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1PmnVkh0WKSJ5v9Thr4NGNlrHdxuu3Ygz#list",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1iBLsa2ayHOf7AoEiIrx3XkoHUbX1P6G4#list",
    Física: "https://drive.google.com/embeddedfolderview?id=1ArM4gggmMj-atwXRnGK6oEhC6-Dvt4xJ#list",
    Francês: "https://drive.google.com/embeddedfolderview?id=1qS3s8iuZyyirnKFa5iiBFtimsxQUph3t#list",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1OSSoRhqRCGeHJExiqTjOlZSwd7F4C5fY#list",
    Inglês: "https://drive.google.com/embeddedfolderview?id=13iEveDhVEApQWXjUIcbLY-qm4_PO0aks#list",
    Matemática: "https://drive.google.com/embeddedfolderview?id=1aLX1tZ-hUkZaXcw91sojWXdu-kfEuGfq#list",
    Português: "https://drive.google.com/embeddedfolderview?id=1U6Fp1_ilV0TpN7PEDf8vsioEP8l3wl7#list",
    Química: "https://drive.google.com/embeddedfolderview?id=1e4hC6PuoxC7zk9aXDiaR4f20YtHyk2i6#list",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=1LaIDADxJpkjN05rMttk_uVliVXICQ_XY#list",
  },
  "11": {
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1SdWjoKYCyeVlR56m2rHpyGNWoKAJu-VV#list",
    Biologia: "https://drive.google.com/embeddedfolderview?id=11wNMAor0k37cENLFhThD8I2g-bW5vTDB#list",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1du_cgMu4O2AOYPAp_NCXwSYCvcH7ys3A#list",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1b_PvSSpQV4y4hh2e9-4i50GYD66OeNFp#list",
    Filosofia: "https://drive.google.com/embeddedfolderview?id=1ms1qkaBy7dfbqS7XDaCZm4SR-hON26OX#list",
    Física: "https://drive.google.com/embeddedfolderview?id=19JTWjZXIiKOX277n05wDKqwR7BxyTbId#list",
    Francês: "https://drive.google.com/embeddedfolderview?id=1u1Hcpl842WDlJ8XK7fyLpaeuLOmJF_ry#list",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1FM7Ugrrg2w8cJP0QF4f7fscY6r3o1uyl#list",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1trbf14oKVJqFDtSct8D3EUfkmcVehTTm#list",
    Matemática: "https://drive.google.com/embeddedfolderview?id=1lIOAQ0lX8_e5wIkvNqB6deMid9N0x8Zr#list",
    Português: "https://drive.google.com/embeddedfolderview?id=1jm9X6AsehHVP2eFg_sLasz_rH9Ub3WnS#list",
    Psicopedagogia: "https://drive.google.com/embeddedfolderview?id=1ppBJkXve4Dd-o5GZmqL6bmiEIdjJD1YP#list",
    Química: "https://drive.google.com/embeddedfolderview?id=1jSx8oBosBcNCI5TrCFOQfZULbQsBTCav#list",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=109RJwXyOWiTS_HGrJgGxBa8hUi4eZUrq#list",
  },
  "12": {
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1AQWQJVgneO5nwZS9pD_gzBLEippVDPta#list",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1THPVsJvGodojp4zUA2B3SHneYoRN_V-J#list",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1jTBKgzYdhrDgJEmqQz7TZvbqlJq9Daop#list",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1ifQd-UIGYsiwt0G1d7EjeJh7JPZcpHgc#list",
    Filosofia: "https://drive.google.com/embeddedfolderview?id=11xNB5LQZPt_O7vgDjQEpym77zu19PbLS#list",
    Física: "https://drive.google.com/embeddedfolderview?id=1MNnd0rHkqOL9qATYW_R7tI4X66rVcy97#list",
    Francês: "https://drive.google.com/embeddedfolderview?id=1OwhUVTLUxu9AG42zZSC8QcrDmxX2ov9r#list",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1IFqaUIiGBIlJthYfnouqzC-Q7I_qGdnL#list",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1J6CcBBpAx-jEV7_RNb0Fxwg7upRDpfOb#list",
    Matemática: "https://drive.google.com/embeddedfolderview?id=18CS8mvoWdokD4J45zR4lCpaRG65YfWRa#list",
    Português: "https://drive.google.com/embeddedfolderview?id=1FReIBDbPqxufzl3WSq9OVw0DVWL1qz-N#list",
    Psicologia: "https://drive.google.com/embeddedfolderview?id=1nnWlq5fHDhGutpDyTEz6wPZWXUS5ZnM5#list",
    Química: "https://drive.google.com/embeddedfolderview?id=1aX___H9vT2afY-snvXyiu3ri4-RZT-Ig#list",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=10wZcL32sJw4PgmO47pJfAnloTVNHhATl#list",
  },
}

// Link da vitrine - SUBSTITUA ESTE LINK PELO SEU DRIVE DA VITRINE
export const vitrineLink = "https://drive.google.com/embeddedfolderview?id=1-7D3Q7R9Tw1Hk6pp_laEgW6tXSoON0bZ#list"

// Links dos exames por classe - SUBSTITUA ESTES LINKS PELOS SEUS DRIVES DE EXAMES
export const examLinks = {
  "9": "https://drive.google.com/embeddedfolderview?id=1ZVtieYjSPFx-vckgzyq1gAdz17B5LbxQ#list",
  "10": "https://drive.google.com/embeddedfolderview?id=1gXHubdt9bCoYL-87vmoqOaJx7uZ5ydWa#list",
  "12": "https://drive.google.com/embeddedfolderview?id=1cjVVcpOefx7jlzZiZ7qxkHBjmS11qYEg#list",
}
