// Dados organizados por classe e disciplina com links convertidos para embeddedfolderview
export const driveLinks = {
  "7": {
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1OPs3eEolF74hMP4idDMXf_nkLq5ZiTud#grid",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1AXolnDK_45PWzwqx9XboiUFx2-Lg1V8B#grid",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1hnzNHKrrkIdnmIgR3A8SsHvfNPTQcxlJ#grid",
    Física: "https://drive.google.com/embeddedfolderview?id=1EunIY_c77MO8ebAYuNPjHOFHsZBAdkm8#grid",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1y4vLsIcHJUdcplr1B1bDMhh_UbO6nCPu#grid",
    História: "https://drive.google.com/embeddedfolderview?id=12fS48y2G7o7w_kI1S8Gl9_pot53_4Nsc#grid",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1f0Ur2aRkcJLUreyInf9OL6Nzilij6-qj#grid",
    Matemática: "https://drive.google.com/embeddedfolderview?id=142J3A4WaKhJrdXGHLa_S64wGCJ-OYvh6#grid",
    Química: "https://drive.google.com/embeddedfolderview?id=1oXViKXWsmNLMA8LTjn5M36coZA3eb7xW#grid",
    "lingua portuguesa": "https://drive.google.com/embeddedfolderview?id=1U0FIeYsGbcTN44Y-OLPFciiNxUJSlX1l#grid",
  },
  "8": {
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1L4SlK7PqGblqqSM9ARIZfw8WZYOdNoG5#grid",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1oyCxsd1rklg4fK4qfngvrtyRm4YqvlXa#grid",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1EH2TIk8_O0wCGdW4d53K4GgGp2fW_3ne#grid",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1EH2TIk8_O0wCGdW4d53K4GgGp2fW_3ne#grid",
    Física: "https://drive.google.com/embeddedfolderview?id=1nNngc6I4TwNsyXTshR3INkRpv7e0tTlw#grid",
    Francês: "https://drive.google.com/embeddedfolderview?id=1nNngc6I4TwNsyXTshR3INkRpv7e0tTlw#grid",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1E46aPoE1GJGnNav0C529EZO9NOMRST3k#grid",
    História: "https://drive.google.com/embeddedfolderview?id=16B96Jh_dCZTcNJT1qLvuWtvLnPBZtixj#grid",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1EdXSnug3mGrVCL6TMG1wxFqU6St18HYX#grid",
    Matemática: "https://drive.google.com/embeddedfolderview?id=1bEo6gmLhwwj8ipD-ZSeI-Ku19qYRXviA#grid",
    Português: "https://drive.google.com/embeddedfolderview?id=1hMkQyeg6uwTqAyTx_qvXNFQYYHsd6wl2#grid",
    Química: "https://drive.google.com/embeddedfolderview?id=1nMzI30aZ2OwrZPz0T-DqCSqPtX3r2K4v#grid",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=1mFJqkPgj5_NPqrHpdtu5SPjbbZ0eh_UX#grid",
  },
  "9": {
    História: "https://drive.google.com/embeddedfolderview?id=14xxHBl70X8g7J6Bjr3k7H2WZJM0dSoCq#grid"
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=16oNimQladjjAsJkKUjk6RoaeY2ko4tnM#grid",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1j2QcwJDspT1ez-7aCK2S3Xd-uFNXmx5P#grid",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1K0fZSjMGoyHbqesSuIAKQLlsuA89nS4w#grid",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1K0fZSjMGoyHbqesSuIAKQLlsuA89nS4w#grid",
    Física: "https://drive.google.com/embeddedfolderview?id=17AtSatgnAipSET7DX97-0akM208iYs25#grid",
    Francês: "https://drive.google.com/embeddedfolderview?id=1D1Z9Zoe0uHB7IrGMe4RSeFfE_N3JGYdC#grid",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1D1Z9Zoe0uHB7IrGMe4RSeFfE_N3JGYdC#grid",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1YO5pN5TY9LGXxVw01cNj9sYbfz-Pv4JV#grid",
    Matemática: "https://drive.google.com/embeddedfolderview?id=1I3qsHGKO_a6bfwep8CKbCk3_hbnEIQIr#grid",
    Português: "https://drive.google.com/embeddedfolderview?id=19mVLWWktplhwLp2aIKbaFhbvouwCvinx#grid",
    Química: "https://drive.google.com/embeddedfolderview?id=1UpsfIlDwHUbWGEb-iGytW5pBxor2v25X#grid",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=19tFVkiJziUtTgN2gaUTtfCj4MdG_oDHB#grid",
  },
  "10": {

    História:"https://drive.google.com/embeddedfolderview?id=1qpPpBDwiB8sCIrIwoVsehKZe1iX6taJq#grid",
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1JjgMeaOwVDdYv86yWhKzSLfwFk2SCf4F#grid",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1hcfYAvtB0m2583wSM_MASJS7tNTmHeDf#grid",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1PmnVkh0WKSJ5v9Thr4NGNlrHdxuu3Ygz#grid",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1iBLsa2ayHOf7AoEiIrx3XkoHUbX1P6G4#grid",
    Física: "https://drive.google.com/embeddedfolderview?id=1ArM4gggmMj-atwXRnGK6oEhC6-Dvt4xJ#grid",
    Francês: "https://drive.google.com/embeddedfolderview?id=1qS3s8iuZyyirnKFa5iiBFtimsxQUph3t#grid",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1OSSoRhqRCGeHJExiqTjOlZSwd7F4C5fY#grid",
    Inglês: "https://drive.google.com/embeddedfolderview?id=13iEveDhVEApQWXjUIcbLY-qm4_PO0aks#grid",
    Matemática: "https://drive.google.com/embeddedfolderview?id=1aLX1tZ-hUkZaXcw91sojWXdu-kfEuGfq#grid",
    Português: "https://drive.google.com/embeddedfolderview?id=1U6Fp1_ilV0TpN7PEDf8vsioEP8l3wl7#grid",
    Química: "https://drive.google.com/embeddedfolderview?id=1e4hC6PuoxC7zk9aXDiaR4f20YtHyk2i6#grid",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=1LaIDADxJpkjN05rMttk_uVliVXICQ_XY#grid",
  },
  "11": {
  História:"https://drive.google.com/embeddedfolderview?id=1-b1EsYDUqItfLsgX0hdW_nzDNqLK9eaP#grid",
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1SdWjoKYCyeVlR56m2rHpyGNWoKAJu-VV#grid",
    Biologia: "https://drive.google.com/embeddedfolderview?id=11wNMAor0k37cENLFhThD8I2g-bW5vTDB#grid",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1du_cgMu4O2AOYPAp_NCXwSYCvcH7ys3A#grid",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1b_PvSSpQV4y4hh2e9-4i50GYD66OeNFp#grid",
    Filosofia: "https://drive.google.com/embeddedfolderview?id=1ms1qkaBy7dfbqS7XDaCZm4SR-hON26OX#grid",
    Física: "https://drive.google.com/embeddedfolderview?id=19JTWjZXIiKOX277n05wDKqwR7BxyTbId#grid",
    Francês: "https://drive.google.com/embeddedfolderview?id=1u1Hcpl842WDlJ8XK7fyLpaeuLOmJF_ry#grid",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1FM7Ugrrg2w8cJP0QF4f7fscY6r3o1uyl#grid",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1trbf14oKVJqFDtSct8D3EUfkmcVehTTm#grid",
    Matemática: "https://drive.google.com/embeddedfolderview?id=1lIOAQ0lX8_e5wIkvNqB6deMid9N0x8Zr#grid",
    Português: "https://drive.google.com/embeddedfolderview?id=1jm9X6AsehHVP2eFg_sLasz_rH9Ub3WnS#grid",
    Psicopedagogia: "https://drive.google.com/embeddedfolderview?id=1ppBJkXve4Dd-o5GZmqL6bmiEIdjJD1YP#grid",
    Química: "https://drive.google.com/embeddedfolderview?id=1jSx8oBosBcNCI5TrCFOQfZULbQsBTCav#grid",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=109RJwXyOWiTS_HGrJgGxBa8hUi4eZUrq#grid",
  },
  "12": {

    História:"https://drive.google.com/embeddedfolderview?id=14D-aai-m5fqEBr-31SrBeFDYaQ6aYcFp#grid",
    Agropecuária: "https://drive.google.com/embeddedfolderview?id=1AQWQJVgneO5nwZS9pD_gzBLEippVDPta#grid",
    Biologia: "https://drive.google.com/embeddedfolderview?id=1THPVsJvGodojp4zUA2B3SHneYoRN_V-J#grid",
    "Educação Física": "https://drive.google.com/embeddedfolderview?id=1jTBKgzYdhrDgJEmqQz7TZvbqlJq9Daop#grid",
    "Educação Visual": "https://drive.google.com/embeddedfolderview?id=1ifQd-UIGYsiwt0G1d7EjeJh7JPZcpHgc#grid",
    Filosofia: "https://drive.google.com/embeddedfolderview?id=11xNB5LQZPt_O7vgDjQEpym77zu19PbLS#grid",
    Física: "https://drive.google.com/embeddedfolderview?id=1MNnd0rHkqOL9qATYW_R7tI4X66rVcy97#grid",
    Francês: "https://drive.google.com/embeddedfolderview?id=1OwhUVTLUxu9AG42zZSC8QcrDmxX2ov9r#grid",
    Geografia: "https://drive.google.com/embeddedfolderview?id=1IFqaUIiGBIlJthYfnouqzC-Q7I_qGdnL#grid",
    Inglês: "https://drive.google.com/embeddedfolderview?id=1J6CcBBpAx-jEV7_RNb0Fxwg7upRDpfOb#grid",
    Matemática: "https://drive.google.com/embeddedfolderview?id=18CS8mvoWdokD4J45zR4lCpaRG65YfWRa#grid",
    Português: "https://drive.google.com/embeddedfolderview?id=1FReIBDbPqxufzl3WSq9OVw0DVWL1qz-N#grid",
    Psicologia: "https://drive.google.com/embeddedfolderview?id=1nnWlq5fHDhGutpDyTEz6wPZWXUS5ZnM5#grid",
    Química: "https://drive.google.com/embeddedfolderview?id=1aX___H9vT2afY-snvXyiu3ri4-RZT-Ig#grid",
    "TIC'S": "https://drive.google.com/embeddedfolderview?id=10wZcL32sJw4PgmO47pJfAnloTVNHhATl#grid",
  },
}

// Link da vitrine - SUBSTITUA ESTE LINK PELO SEU DRIVE DA VITRINE
export const vitrineLink = "https://drive.google.com/embeddedfolderview?id=1-7D3Q7R9Tw1Hk6pp_laEgW6tXSoON0bZ#grid"

// Links dos exames por classe - SUBSTITUA ESTES LINKS PELOS SEUS DRIVES DE EXAMES
export const examLinks = {
  "9": "https://drive.google.com/embeddedfolderview?id=1ZVtieYjSPFx-vckgzyq1gAdz17B5LbxQ#grid",
  "10": "https://drive.google.com/embeddedfolderview?id=1gXHubdt9bCoYL-87vmoqOaJx7uZ5ydWa#grid",
  "12": "https://drive.google.com/embeddedfolderview?id=1cjVVcpOefx7jlzZiZ7qxkHBjmS11qYEg#grid",
}
